version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./app/data:/app/app/data
    env_file:
      - .env
    restart: on-failure:3
