name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: linkshrink:test

      - name: Verify Docker image
        run: |
          docker images
          docker run --rm -d -p 5000:5000 --name linkshrink-test linkshrink:test
          sleep 5
          docker ps | grep linkshrink-test
          docker stop linkshrink-test
