name: Deploy on Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: linkshrink:${{ github.ref_name }}

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Save Docker image
        run: |
          docker save -o linkshrink.tar linkshrink:${{ github.ref_name }}
          ls -la linkshrink.tar

      - name: Transfer and deploy image
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TAILSCALE_SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "linkshrink.tar"
          target: "/tmp"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TAILSCALE_SERVER_NAME }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i /tmp/linkshrink.tar
            docker stop linkshrink || true
            docker rm linkshrink || true
            docker run -d -p 3200:5000 --name linkshrink \
              -v /opt/linkshrink:/app/app/data/ \
              --restart always \
              linkshrink:${{ github.ref_name }}
            rm /tmp/linkshrink.tar
